export { default as Auth } from 'pages/auth'
export { default as Dashboard } from 'pages/dashboard'
export { default as Jabber } from 'pages/jabber'
export { default as Landing } from 'pages/landing'
export { default as Mail } from 'pages/mail'
export { default as Blog } from 'pages/blog'
